theme: jekyll-theme-cayman
title: Marc Grover's Data Science Portfolio
description: Projects and analytics implementing Data Science, Machine Learning and AI
markdown: kramdown
kramdown:
  math_engine: mathjax
